Add gcp_monitoring_alert_policy table
turbot/steampipe-plugin-gcp pull request #168
Opened 2021-04-07 13:58 UTC by Paulami30

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined
SETUP: tests/gcp_monitoring_alert_policy []
PRETEST: tests/gcp_monitoring_alert_policy
TEST: tests/gcp_monitoring_alert_policy
Running terraform
data.google_client_config.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
google_monitoring_alert_policy.named_test_resource: Creating...
google_monitoring_alert_policy.named_test_resource: Still creating... [10s elapsed]
google_monitoring_alert_policy.named_test_resource: Still creating... [20s elapsed]
google_monitoring_alert_policy.named_test_resource: Creation complete after 27s [id=projects/pikachu-aaa/alertPolicies/17649582712052525405]
data.template_file.resource_aka: Refreshing state...
Warning: Deprecated Resource
The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Outputs:
project_id = pikachu-aaa
resource_aka = gcp://monitoring.googleapis.com/projects/pikachu-aaa/alertPolicies/17649582712052525405
resource_id = projects/pikachu-aaa/alertPolicies/17649582712052525405
resource_name = turbottest12044
Running SQL query: test-get-query.sql
[
  {
    "combiner": "OR",
    "display_name": "turbottest12044",
    "documentation": {
      "content": "This is for testing purpose",
      "mimeType": "text/markdown"
    },
    "enabled": true,
    "location": "global",
    "name": "17649582712052525405",
    "project": "pikachu-aaa",
    "user_labels": {
      "foo": "bar"
    }
  }
]
✔ PASSED
Running SQL query: test-hydrate-query.sql
[
  {
    "combiner": "OR",
    "display_name": "turbottest12044",
    "enabled": true,
    "name": "17649582712052525405",
    "project": "pikachu-aaa",
    "tags": {
      "foo": "bar"
    }
  }
]
✔ PASSED
Running SQL query: test-list-query.sql
[
  {
    "combiner": "OR",
    "display_name": "turbottest12044",
    "name": "17649582712052525405"
  }
]
✔ PASSED
Running SQL query: test-not-found-query.sql
null
✔ PASSED
POSTTEST: tests/gcp_monitoring_alert_policy
TEARDOWN: tests/gcp_monitoring_alert_policy
SUMMARY:
1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info
select
  display_name,
  name,
  enabled,
  documentation ->> 'content' as doc_content,
  tags
from
  gcp_monitoring_alert_policy;
  
+--------------+---------------------+---------+-------------+--------+
| display_name | name                | enabled | doc_content | tags   |
+--------------+---------------------+---------+-------------+--------+
| test-alert   | 1385080259726788053 | true    | testing     | <null> |
+--------------+---------------------+---------+-------------+--------+

### Get the creation record for each alert policy
select
  display_name,
  name,
  creation_record ->> 'mutateTime' as mutation_time,
  creation_record ->> 'mutatedBy' as mutated_by
from
  gcp_monitoring_alert_policy;
  
  +--------------+---------------------+--------------------------------+--------------------+
| display_name | name                | mutation_time                  | mutated_by         |
+--------------+---------------------+--------------------------------+--------------------+
| test-alert   | 1385080259726788053 | 2021-04-07T07:11:34.362714499Z | paulami@turbot.com |
+--------------+---------------------+--------------------------------+--------------------+

### Get the condition details for each alert policy
select
  display_name,
  con ->> 'displayName' as filter_display_name,
  con -> 'conditionThreshold' ->> 'filter' as filter,
  con -> 'conditionThreshold' ->> 'thresholdValue' as threshold_value,
  con -> 'conditionThreshold' ->> 'trigger' as trigger
from
  gcp_monitoring_alert_policy,
  jsonb_array_elements(conditions) as con;
  
  +--------------+-----------------------------------------+----------------------------------------------------------------------------------------------------
| display_name | filter_display_name                     | filter                                                                                             
+--------------+-----------------------------------------+----------------------------------------------------------------------------------------------------
| test-alert   | VM Instance - CPU usage for test [RATE] | metric.type="compute.googleapis.com/instance/cpu/usage_time" resource.type="gce_instance" metric.la
+--------------+-----------------------------------------+----------------------------------------------------------------------------------------------------

```
</details>

2021-04-12 05:34 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +			},
Not needed
```suggestion
```

2021-04-12 05:34 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +			},
Not needed
```suggestion
```

2021-04-12 05:35 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +			{
Add `title` before `tags` column

2021-04-12 05:46 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +				Transform:   transform.FromValue(),
Can we use `name` to get the project?

2021-04-12 05:52 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +}
Do we need hydrate function to build the aka? or, we can use transform function?

2021-04-12 05:58 UTC, Subhajit97 commented on docs/tables/gcp_monitoring_alert_policy.md
> +# Table:  gcp_monitoring_alert_policy
```suggestion
# Table: gcp_monitoring_alert_policy
```

2021-04-12 06:01 UTC, Subhajit97 requested changes
@Paulami30 There are few changes required. Please see comments, thanks!
Can you also add the queries for the recommendations mentioned in the issue?

2021-04-13 10:54 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +				Name:        "enabled",
Add this column below `name`.

2021-04-13 10:55 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_JSON,
```

2021-04-13 10:55 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +				Transform:   transform.FromP(getMonitoringAlertPolicyAka, "Akas"),
Do we need `FromP` to get a single property value?

2021-04-13 10:55 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +
```suggestion
```

2021-04-13 10:57 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +	req, err := service.Projects.AlertPolicies.Get("projects/" + project + "/alertPolicies/" + name).Do()
Is it correct?
As per the api `Name` includes both projectID and resourceID
![image](https://user-images.githubusercontent.com/38218418/114542126-29b88f80-9c75-11eb-9dce-808c0634a19c.png)

2021-04-13 10:57 UTC, Subhajit97 commented on gcp/table_gcp_monitoring_alert_policy.go
> +	Akas := []string{"gcp://monitoring.googleapis.com/" + alertPolicy.Name}
```suggestion
	akas := []string{"gcp://monitoring.googleapis.com/" + alertPolicy.Name}
```

2021-04-13 12:56 UTC, Subhajit97 approved these changes
LGTM

2021-04-13 14:15 UTC, rajmohanty17 approved these changes
LGTM

2021-04-14 19:09 UTC, cbruno10 approved these changes

2021-04-14 19:09 UTC, merged