Add table gcp_project_organization_policy. closes #186
turbot/steampipe-plugin-gcp pull request #204
Opened 2021-05-14 14:23 UTC by Priyanka585464

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/gcp_projects_organization_policy []

PRETEST: tests/gcp_projects_organization_policy

TEST: tests/gcp_projects_organization_policy
Running terraform
data.google_client_config.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
google_project_organization_policy.named_test_resource: Creating...
google_project_organization_policy.named_test_resource: Creation complete after 3s [id=pikachu-aaa:serviceuser.services]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

project_aka = gcp://cloudresourcemanager.googleapis.com/projects/pikachu-aaa
project_id = pikachu-aaa
resource_id = serviceuser.services
resource_name = turbottest73472
resource_title = constraints/serviceuser.services

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "gcp://cloudresourcemanager.googleapis.com/projects/pikachu-aaa"
    ],
    "project": "pikachu-aaa",
    "title": "constraints/serviceuser.services"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "akas": [
      "gcp://cloudresourcemanager.googleapis.com/projects/pikachu-aaa"
    ],
    "location": "global",
    "project": "pikachu-aaa",
    "title": "constraints/serviceuser.services"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "gcp://cloudresourcemanager.googleapis.com/projects/pikachu-aaa"
    ],
    "title": "constraints/serviceuser.services"
  }
]
✔ PASSED

POSTTEST: tests/gcp_projects_organization_policy

TEARDOWN: tests/gcp_projects_organization_policy

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  *
from
  gcp_projects_organization_policy;
```
```
+----------------------------------------+---------------------+---------+--------------+-----------------------+----------------+-----------------+----------------------------------------------------+---
| id                                     | update_time         | version | etag         | list_policy           | boolean_policy | restore_default | title                                              | ak
+----------------------------------------+---------------------+---------+--------------+-----------------------+----------------+-----------------+----------------------------------------------------+---
| run.allowedBinaryAuthorizationPolicies | 2021-05-13 06:25:19 | 0       | BwXCMDD86pE= | {"allValues":"ALLOW"} | <null>         | <null>          | constraints/run.allowedBinaryAuthorizationPolicies | ["
+----------------------------------------+---------------------+---------+--------------+-----------------------+----------------+-----------------+----------------------------------------------------+---
```

### Check policy's previously updated time by server

```sql
select
  id,
  version,
  update_time
from
  gcp_projects_organization_policy,
```
```
+----------------------------------------+---------+---------------------+
| id                                     | version | update_time         |
+----------------------------------------+---------+---------------------+
| run.allowedBinaryAuthorizationPolicies | 0       | 2021-05-13 06:25:19 |
+----------------------------------------+---------+---------------------+
```

### Check the policy values given to constraint.

```sql
select
  id,
  version,
  list_policy ->> 'allValues' as policy_value
from
  gcp_projects_organization_policy;
```
```
+----------------------------------------+---------+--------------+
| id                                     | version | policy_value |
+----------------------------------------+---------+--------------+
| run.allowedBinaryAuthorizationPolicies | 0       | ALLOW        |
+----------------------------------------+---------+--------------+
```

2021-05-20 06:00 UTC, Subhajit97 commented on gcp/plugin.go
> +			"gcp_projects_organization_policy":    tableGcpProjectsOrganizationPolicy(ctx),
```suggestion
			"gcp_project_organization_policy":    tableGcpProjectOrganizationPolicy(ctx),
```

2021-05-20 06:00 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +		Description: "GCP Projects Organization Policy",
```suggestion
		Description: "GCP Project Organization Policy",
```

2021-05-20 06:01 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +			// standard steampipe columns
```suggestion
			// Steampipe standard columns
```

2021-05-20 06:01 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +				Transform:   transform.FromField("Constraint"),
Can we use `Transform:   transform.FromField("Constraint").Transform(lastPathElement),` for `title`?

2021-05-20 06:01 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +//// FETCH FUNCTIONS
```suggestion
//// LIST FUNCTION
```

2021-05-20 06:01 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +func listGcpProjectsOrganizationPolicies(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```suggestion
func listGcpProjectOrganizationPolicies(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
```

2021-05-20 06:02 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +	}
```suggestion
	rb := &cloudresourcemanager.ListOrgPoliciesRequest{}
```

2021-05-20 06:02 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +func getGcpProjectsOrganizationPolicy(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getGcpProjectOrganizationPolicy(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-05-20 06:03 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +	req, err := service.Projects.GetOrgPolicy("projects/"+project, rb).Do()
```suggestion
	req, err := service.Projects.GetOrgPolicy("projects/" + project, rb).Do()
```

2021-05-20 06:04 UTC, Subhajit97 commented on gcp/table_gcp_projects_organization_policy.go
> +	}
Do we need to return `title` from this function, since we can use `id`?

2021-05-20 06:05 UTC, Subhajit97 commented on docs/tables/gcp_projects_organization_policy.md
> +### Check the policy values given to constraint.
```suggestion
### Check the policy values given to constraint
```

2021-05-28 14:50 UTC, Subhajit97 commented on docs/tables/gcp_project_organization_policy.md
> +  *
Can we query specific columns, instead of `*`?

2021-05-28 14:51 UTC, Subhajit97 commented on gcp/table_gcp_project_organization_policy.go
> +func tableGcpProjectsOrganizationPolicy(ctx context.Context) *plugin.Table {
```suggestion
func tableGcpProjectOrganizationPolicy(ctx context.Context) *plugin.Table {
```

2021-05-28 14:52 UTC, Subhajit97 commented on gcp/table_gcp_project_organization_policy.go
> +	plugin.Logger(ctx).Trace("listGcpProjectOrganizationPolicies", "GCP_PROJECT: ", project)
```suggestion
```

2021-05-28 14:52 UTC, Subhajit97 commented on gcp/table_gcp_project_organization_policy.go
> +
```suggestion
```

2021-05-28 14:52 UTC, Subhajit97 commented on gcp/table_gcp_project_organization_policy.go
> +	resp := service.Projects.ListOrgPolicies("projects/"+project, rb)
```suggestion
	resp := service.Projects.ListOrgPolicies("projects/" + project, rb)
```

2021-05-28 14:55 UTC, Subhajit97 commented on gcp/table_gcp_project_organization_policy.go
> +	title := strings.ToUpper(project) + " Org Policy"
@Priyanka585464 Is this title `required`?
You are not using this `title` value anywhere.
Currently the `title` is using `constraint` value
https://github.com/turbot/steampipe-plugin-gcp/pull/204/files#diff-90f64bc506bbef72770fec8f8ca390942b03e818c0b89357a21e3517f02b28b8R70

2021-05-28 14:56 UTC, Subhajit97 commented on gcp-test/tests/gcp_project_organization_policy/variables.tf
> +  default     = "pikachu-aaa"
```suggestion
  default     = "niteowl-aaa"
```

2021-05-28 14:57 UTC, Subhajit97 requested changes
@Priyanka585464 There are few more changes required. Please see comments, thanks!

2021-06-10 15:22 UTC, Subhajit97 approved these changes
LGTM

2021-06-21 08:19 UTC, rajmohanty17 approved these changes
LGTM

2021-06-21 21:14 UTC, cbruno10 approved these changes

2021-06-21 21:14 UTC, merged