Add table gcp_disk_metric_read_ops_hourly #223
turbot/steampipe-plugin-gcp pull request #260
Opened 2021-06-28 11:23 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  instance_id,
  minimum,
  maximum,
  average,
  sample_count
from
  gcp_disk_metric_read_ops_hourly
order by
  instance_id;

+-------------+---------+---------+----------------------+--------------+
| instance_id | minimum | maximum | average              | sample_count |
+-------------+---------+---------+----------------------+--------------+
| instance-1  | 0       | 57      | 3.057142857142857    | 35           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 61           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 61           |
| instance-1  | 0       | 2468    | 136.5142857142857    | 35           |
| instance-1  | 0       | 4698    | 188.23333333333332   | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 558     | 17.866666666666667   | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 2       | 0.06666666666666667  | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 23      | 0.7                  | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 1       | 0.016666666666666666 | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 74      | 1.7833333333333334   | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 61           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 456     | 10.8                 | 60           |
| instance-1  | 0       | 304     | 7.133333333333334    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 3228    | 79.55                | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 61           |
| instance-1  | 0       | 32      | 0.75                 | 60           |
| instance-1  | 0       | 0       | 0                    | 61           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 4006    | 81.40677966101696    | 59           |
| instance-1  | 0       | 0       | 0                    | 60           |
| instance-1  | 0       | 0       | 0                    | 60           |
+-------------+---------+---------+----------------------+--------------+
```

### Intervals averaging over 100 connections

```sql
select
  instance_id,
  round(minimum::numeric,2) as min_connection,
  round(maximum::numeric,2) as max_connection,
  round(average::numeric,2) as avg_connection,
  sample_count
from
  gcp_disk_metric_read_ops_hourly
where average > 100
order by
  instance_id;

+-------------+----------------+----------------+----------------+--------------+
| instance_id | min_connection | max_connection | avg_connection | sample_count |
+-------------+----------------+----------------+----------------+--------------+
| instance-1  | 0.00           | 2468.00        | 136.51         | 35           |
| instance-1  | 0.00           | 4698.00        | 188.23         | 60           |
| instance-1  | 0.00           | 3228.00        | 779.83         | 6            |
+-------------+----------------+----------------+----------------+--------------+
```

### Intervals averaging fewer than 10 connections

```sql
select
  instance_id,
  round(minimum::numeric,2) as min_connection,
  round(maximum::numeric,2) as max_connection,
  round(average::numeric,2) as avg_connection,
  sample_count
from
  gcp_disk_metric_read_ops_hourly
where average < 10
order by
  instance_id;

+-------------+----------------+----------------+----------------+--------------+
| instance_id | min_connection | max_connection | avg_connection | sample_count |
+-------------+----------------+----------------+----------------+--------------+
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 61           |
| instance-1  | 0.00           | 57.00          | 3.06           | 35           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00           | 0.00           | 0.00           | 60           |
| instance-1  | 0.00            [...]

2021-06-28 12:23 UTC, Subhajit97 commented on gcp/table_gcp_disk_metric_read_ops_hourly.go
> +		Description: "GCP Compute Disk Daily connections",
```suggestion
		Description: "GCP Compute Disk Metrics -Read Ops (Hourly)",
```

2021-06-28 12:24 UTC, Subhajit97 commented on gcp/table_gcp_disk_metric_read_ops_hourly.go
> +	instanceInfo := h.Item.(*compute.Instance)
Is it correct?
Why are we fetching `Instance` details, since the table stores `disk` metrics?

2021-06-28 12:25 UTC, Subhajit97 requested changes
@rajeshbal65 Please verify the table and test properly

2021-06-30 11:08 UTC, Subhajit97 approved these changes

2021-06-30 16:16 UTC, rajmohanty17 approved these changes
LGTM

2021-07-01 18:37 UTC, cbruno10 approved these changes

2021-07-01 18:37 UTC, merged